In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import accuracy_score

file_path = r'C:\Users\THASNEEM FATHIMA\Downloads\smoteagain.csv'
data = pd.read_csv(file_path)

target_column = "num"
X = data.drop(columns=[target_column])
y = data[target_column]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

et_classifier = ExtraTreesClassifier(n_estimators=100, random_state=42)
et_classifier.fit(X_train, y_train)

y_pred = et_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)



Accuracy: 0.9710144927536232


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import accuracy_score

file_path = r'C:\Users\THASNEEM FATHIMA\Downloads\fcbfdata.csv'
data = pd.read_csv(file_path)

target_column = "num"
X = data.drop(columns=[target_column])
y = data[target_column]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

et_classifier = ExtraTreesClassifier(n_estimators=100, random_state=42)
et_classifier.fit(X_train, y_train)

y_pred = et_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)



Accuracy: 0.9637681159420289


In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import ExtraTreesClassifier
import pandas as pd

data = pd.read_csv(r'C:\Users\THASNEEM FATHIMA\Downloads\aco2.csv')

X = data.drop('num', axis=1)
y = data['num']

param_grid = {
    'n_estimators': [81, 85, 90, 95, 100]
}

et_classifier = ExtraTreesClassifier(random_state=42)
print("Initial parameter:", et_classifier.get_params()['n_estimators'])
grid_search = GridSearchCV(estimator=et_classifier, param_grid=param_grid, cv=5, scoring='accuracy', verbose=2)

grid_search.fit(X, y)

print("Best parameter:", grid_search.best_params_)


Initial parameter: 100
Fitting 5 folds for each of 5 candidates, totalling 25 fits
[CV] END ....................................n_estimators=81; total time=   0.0s
[CV] END ....................................n_estimators=81; total time=   0.0s
[CV] END ....................................n_estimators=81; total time=   0.0s
[CV] END ....................................n_estimators=81; total time=   0.0s
[CV] END ....................................n_estimators=81; total time=   0.0s
[CV] END ....................................n_estimators=85; total time=   0.0s
[CV] END ....................................n_estimators=85; total time=   0.0s
[CV] END ....................................n_estimators=85; total time=   0.0s
[CV] END ....................................n_estimators=85; total time=   0.0s
[CV] END ....................................n_estimators=85; total time=   0.0s
[CV] END ....................................n_estimators=90; total time=   0.0s
[CV] END .................

In [7]:
import time
import psutil
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import accuracy_score
from scipy.sparse import csr_matrix
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report

def memory_usage():
    process = psutil.Process()
    return process.memory_info().rss / 1024 ** 2
data = pd.read_csv('/content/sample_data/aco2.csv')
X = data.drop('num', axis=1).astype(np.float32)
y = data['num']
X = csr_matrix(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

start_time = time.time()

clf = ExtraTreesClassifier(n_estimators=80,max_depth=17, max_features=3, random_state=42)
clf.fit(X_train, y_train)

training_time = time.time() - start_time
training_time = time.time() - start_time
y_pred_train = clf.predict(X_train)
cm = confusion_matrix(y_train, y_pred_train)

cr = classification_report(y_train, y_pred_train)
training_acc = accuracy_score(y_train, y_pred_train)
print("Training Accuracy:", training_acc)
print("Training Confusion Matrix:")
print(cm)
print("Training Classification Report:")
print(cr)
y_pred_test = clf.predict(X_test)
cm = confusion_matrix(y_test, y_pred_test)
cr = classification_report(y_test, y_pred_test)
testing_acc = accuracy_score(y_test, y_pred_test)
print("Testing Accuracy:", testing_acc)
print("Testing Confusion Matrix:")
print(cm)
print("Testing Classification Report:")
print(cr)
print("Training Time:", training_time, "seconds")
print("Memory Usage:", memory_usage(), "MB")
predicted = cross_val_predict(clf, X, y, cv=5)
bias = np.mean(predicted - y)
variance = np.var(predicted)
print("Bias:", bias)
print("Variance:", variance)

Training Accuracy: 1.0
Training Confusion Matrix:
[[102   0   0   0   0]
 [  0 107   0   0   0]
 [  0   0 113   0   0]
 [  0   0   0 113   0]
 [  0   0   0   0 115]]
Training Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       102
           1       1.00      1.00      1.00       107
           2       1.00      1.00      1.00       113
           3       1.00      1.00      1.00       113
           4       1.00      1.00      1.00       115

    accuracy                           1.00       550
   macro avg       1.00      1.00      1.00       550
weighted avg       1.00      1.00      1.00       550

Testing Accuracy: 0.9855072463768116
Testing Confusion Matrix:
[[16  0  0  1  0]
 [ 0 29  1  0  0]
 [ 0  0 28  0  0]
 [ 0  0  0 25  0]
 [ 0  0  0  0 38]]
Testing Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.94      0.97        17
           1       

In [5]:
import time
import psutil
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from scipy.sparse import csr_matrix
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report

def memory_usage():
    process = psutil.Process()
    return process.memory_info().rss / 1024 ** 2
data = pd.read_csv('/content/sample_data/acorf.csv')
X = data.drop('num', axis=1).astype(np.float32)
y = data['num']
X = csr_matrix(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

start_time = time.time()

clf = RandomForestClassifier(n_estimators=81, random_state=42)
clf.fit(X_train, y_train)

training_time = time.time() - start_time
y_pred_train = clf.predict(X_train)
cm = confusion_matrix(y_train, y_pred_train)

cr = classification_report(y_train, y_pred_train)
training_acc = accuracy_score(y_train, y_pred_train)
print("Training Accuracy:", training_acc)
print("Training Confusion Matrix:")
print(cm)
print("Training Classification Report:")
print(cr)
y_pred_test = clf.predict(X_test)
cm = confusion_matrix(y_test, y_pred_test)
cr = classification_report(y_test, y_pred_test)
testing_acc = accuracy_score(y_test, y_pred_test)
print("Testing Accuracy:", testing_acc)
print("Testing Confusion Matrix:")
print(cm)
print("Testing Classification Report:")
print(cr)
print("Training Time:", training_time, "seconds")
print("Memory Usage:", memory_usage(), "MB")
predicted = cross_val_predict(clf, X, y, cv=5)
bias = np.mean(predicted - y)
variance = np.var(predicted)
print("Bias:", bias)
print("Variance:", variance)

Training Accuracy: 1.0
Training Confusion Matrix:
[[102   0   0   0   0]
 [  0 107   0   0   0]
 [  0   0 113   0   0]
 [  0   0   0 113   0]
 [  0   0   0   0 115]]
Training Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       102
           1       1.00      1.00      1.00       107
           2       1.00      1.00      1.00       113
           3       1.00      1.00      1.00       113
           4       1.00      1.00      1.00       115

    accuracy                           1.00       550
   macro avg       1.00      1.00      1.00       550
weighted avg       1.00      1.00      1.00       550

Testing Accuracy: 0.9347826086956522
Testing Confusion Matrix:
[[16  0  0  1  0]
 [ 2 24  1  2  1]
 [ 0  0 27  1  0]
 [ 0  1  0 24  0]
 [ 0  0  0  0 38]]
Testing Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.94      0.91        17
           1       

In [4]:
import time
import psutil
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import xgboost as xgb
from sklearn.metrics import accuracy_score
from scipy.sparse import csr_matrix
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix, classification_report

def memory_usage():
    process = psutil.Process()
    return process.memory_info().rss / 1024 ** 2
data = pd.read_csv('/content/sample_data/acoxg.csv')
X = data.drop('num', axis=1).astype(np.float32)
y = data['num']
X = csr_matrix(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

start_time = time.time()

model = xgb.XGBClassifier(objective='multi:softmax', num_class=5)
model.fit(X_train, y_train)

training_time = time.time() - start_time
y_pred_train = model.predict(X_train)
cm = confusion_matrix(y_train, y_pred_train)

cr = classification_report(y_train, y_pred_train)
training_acc = accuracy_score(y_train, y_pred_train)
print("Training Accuracy:", training_acc)
print("Training Confusion Matrix:")
print(cm)
print("Training Classification Report:")
print(cr)
y_pred_test = model.predict(X_test)
cm = confusion_matrix(y_test, y_pred_test)
cr = classification_report(y_test, y_pred_test)
testing_acc = accuracy_score(y_test, y_pred_test)
print("Testing Accuracy:", testing_acc)
print("Testing Confusion Matrix:")
print(cm)
print("Testing Classification Report:")
print(cr)
print("Training Time:", training_time, "seconds")
print("Memory Usage:", memory_usage(), "MB")
predicted = cross_val_predict(model, X, y, cv=5)
bias = np.mean(predicted - y)
variance = np.var(predicted)
print("Bias:", bias)
print("Variance:", variance)

Training Accuracy: 1.0
Training Confusion Matrix:
[[102   0   0   0   0]
 [  0 107   0   0   0]
 [  0   0 113   0   0]
 [  0   0   0 113   0]
 [  0   0   0   0 115]]
Training Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       102
           1       1.00      1.00      1.00       107
           2       1.00      1.00      1.00       113
           3       1.00      1.00      1.00       113
           4       1.00      1.00      1.00       115

    accuracy                           1.00       550
   macro avg       1.00      1.00      1.00       550
weighted avg       1.00      1.00      1.00       550

Testing Accuracy: 0.9057971014492754
Testing Confusion Matrix:
[[16  1  0  0  0]
 [ 3 23  2  2  0]
 [ 0  3 24  1  0]
 [ 0  1  0 24  0]
 [ 0  0  0  0 38]]
Testing Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.94      0.89        17
           1       

In [1]:
# import matplotlib.pyplot as plt

# # Data
# deployment = ['Edge', 'Cloud']
# latency = [0.001358, 0.012269]

# # Plotting
# plt.figure(figsize=(8, 6))
# plt.bar(deployment, latency, color=['blue', 'orange'])

# # Adding labels and title
# plt.xlabel('Deployment')
# plt.ylabel('Latency (s)')
# plt.title('Comparison of Deployment Latency')
# plt.ylim(0, max(latency) * 1.1)

# # Display the plot
# plt.show()
